# ------------------------------------------------
# 국가 영어 -> 한국어 전체 번역 추가
# ------------------------------------------------
country_kr = {

    "Afghanistan": "아프가니스탄",
    "Albania": "알바니아",
    "Algeria": "알제리",
    "Andorra": "안도라",
    "Angola": "앙골라",
    "Argentina": "아르헨티나",
    "Armenia": "아르메니아",
    "Australia": "호주",
    "Austria": "오스트리아",
    "Azerbaijan": "아제르바이잔",

    "Bahamas": "바하마",
    "Bahrain": "바레인",
    "Bangladesh": "방글라데시",
    "Belarus": "벨라루스",
    "Belgium": "벨기에",
    "Belize": "벨리즈",
    "Benin": "베냉",
    "Bhutan": "부탄",
    "Bolivia": "볼리비아",
    "Bosnia and Herzegovina": "보스니아 헤르체고비나",
    "Botswana": "보츠와나",
    "Brazil": "브라질",
    "Brunei": "브루나이",
    "Bulgaria": "불가리아",
    "Burkina Faso": "부르키나파소",
    "Burundi": "부룬디",

    "Cambodia": "캄보디아",
    "Cameroon": "카메룬",
    "Canada": "캐나다",
    "Chile": "칠레",
    "China": "중국",
    "Colombia": "콜롬비아",
    "Costa Rica": "코스타리카",
    "Croatia": "크로아티아",
    "Cuba": "쿠바",
    "Cyprus": "키프로스",
    "Czech Republic": "체코",

    "Denmark": "덴마크",
    "Dominican Republic": "도미니카 공화국",

    "Ecuador": "에콰도르",
    "Egypt": "이집트",
    "El Salvador": "엘살바도르",
    "Estonia": "에스토니아",
    "Ethiopia": "에티오피아",

    "Faroe Islands": "페로제도",
    "Finland": "핀란드",
    "France": "프랑스",

    "Georgia": "조지아",
    "Germany": "독일",
    "Ghana": "가나",
    "Greece": "그리스",
    "Greenland": "그린란드",
    "Guatemala": "과테말라",

    "Haiti": "아이티",
    "Honduras": "온두라스",
    "Hungary": "헝가리",

    "Iceland": "아이슬란드",
    "India": "인도",
    "Indonesia": "인도네시아",
    "Iran": "이란",
    "Iraq": "이라크",
    "Ireland": "아일랜드",
    "Israel": "이스라엘",
    "Italy": "이탈리아",

    "Jamaica": "자메이카",
    "Japan": "일본",
    "Jordan": "요르단",

    "Kazakhstan": "카자흐스탄",
    "Kenya": "케냐",
    "Kuwait": "쿠웨이트",
    "Kyrgyzstan": "키르기스스탄",

    "Laos": "라오스",
    "Latvia": "라트비아",
    "Lebanon": "레바논",
    "Libya": "리비아",
    "Lithuania": "리투아니아",
    "Luxembourg": "룩셈부르크",

    "Madagascar": "마다가스카르",
    "Malaysia": "말레이시아",
    "Maldives": "몰디브",
    "Mali": "말리",
    "Mexico": "멕시코",
    "Mongolia": "몽골",
    "Morocco": "모로코",
    "Myanmar": "미얀마",

    "Nepal": "네팔",
    "Netherlands": "네덜란드",
    "New Zealand": "뉴질랜드",
    "Nicaragua": "니카라과",
    "Nigeria": "나이지리아",
    "North Korea": "북한",
    "Norway": "노르웨이",

    "Pakistan": "파키스탄",
    "Panama": "파나마",
    "Paraguay": "파라과이",
    "Peru": "페루",
    "Philippines": "필리핀",
    "Poland": "폴란드",
    "Portugal": "포르투갈",

    "Qatar": "카타르",

    "Romania": "루마니아",
    "Russia": "러시아",
    "Rwanda": "르완다",

    "Saudi Arabia": "사우디아라비아",
    "Senegal": "세네갈",
    "Serbia": "세르비아",
    "Singapore": "싱가포르",
    "Slovakia": "슬로바키아",
    "Slovenia": "슬로베니아",
    "Somalia": "소말리아",
    "South Africa": "남아프리카공화국",
    "South Korea": "대한민국",
    "Spain": "스페인",
    "Sri Lanka": "스리랑카",
    "Sudan": "수단",
    "Sweden": "스웨덴",
    "Switzerland": "스위스",
    "Syria": "시리아",

    "Taiwan": "대만",
    "Tajikistan": "타지키스탄",
    "Thailand": "태국",
    "Tunisia": "튀니지",
    "Turkey": "튀르키예",

    "Ukraine": "우크라이나",
    "United Arab Emirates": "아랍에미리트",
    "United Kingdom": "영국",
    "United States": "미국",
    "Uruguay": "우루과이",
    "Uzbekistan": "우즈베키스탄",

    "Venezuela": "베네수엘라",
    "Vietnam": "베트남",

    "Yemen": "예멘",

    "Zambia": "잠비아",
    "Zimbabwe": "짐바브웨"
}
